# 文章更新
name: update-friends-posts

on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'
  #  branches:
  #    - master
  schedule:
    - cron: '*/30 0-15 * * *'
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id # 自己点的 start
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Set up Python #安装python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6.14
      - name: Install requirements #安装requests
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Update posts #更新
        run: |
          python H_downloader.py
          git config --global user.name "brqs"
          git config --global user.email "3447851674@qq.com"
          git add .
          git commit -m "回传"
          git push origin main
          git pull --rebase origin main
          git push origin main
